### PR TITLE
Do not run inside docker

### LINKED ISSUE #12: Why use docker?
I just started using this action, and it looks well-polished and complete. However, I wonder, why is docker used?

It seems that that adds quite a bit of overhead. I can see a small gain in isolation, but the entire thing already runs in a virtual machine and really only arduino-cli is installed which is just unpacking a zip, so that has little potential to conflict with other steps in the main VM?

The README already mentions calling the script directly as a faster alternative, but that's not so convenient (and more error-prone, typos in env var names are not flagged I expect). Why not just run outside of docker always (or maybe add a `user_docker: yes/no` configuration?

### PR DESCRIPTION
**Pull request by matthijskooijman**
This turns the action into a Javascript to prevent using Docker (which
mostly adds overhead).

As documented by Github, this includes the node_modules directory with
the needed javascript modules. This also adds a minimal package.json,
but without a meaningful version number since this is just to track
dependencies.

This fixes #12.

### CODE REVIEW

**Comment by Legion2** [comment]
I also created my first github action with typescript https://github.com/Legion2/swagger-ui-action. At first it was confusing and difficult because one can't (should not) rely on native binaries like curl and sed, because js actions are executed in the host environment, which could be windows, and not a well-known container. But now I finished the js action and I'm very pleased how the code quality improved by using typescript.

If you need help with this PR, I'll be happy to help.

**Comment by matthijskooijman** [comment]
> At first it was confusing and difficult because one can't (should not) rely on native binaries like curl and sed, because js actions are executed in the host environment, which could be windows, and not a well-known container. 

Hm, that would be problematic, since this PR just executes a bash script using node. It does seem to work in practice, though, but I think that means it only works when used as a step in a workflow that uses a Linux-based environment. That would be a limitation, but I would not consider this problematic (just something to document).

**Comment by ArminJo** [comment]
I converted it now to a "composite run steps" action.

**Comment by Legion2** [comment]
cool

**Comment by matthijskooijman** [comment]
A bit late, but nice that this is now possible. Looking good, thanks!

**Pull request closed without merging**
